-- 1. CREAR TABLA POKEMONS
CREATE TABLE IF NOT EXISTS pokemons (
  id INTEGER PRIMARY KEY,
  name VARCHAR(100) NOT NULL UNIQUE,
  height INTEGER NOT NULL,
  weight INTEGER NOT NULL,
  sprites JSONB NOT NULL,
  moves JSONB NOT NULL
);

-- 2. INSERTAR LOS 10 POKEMON
INSERT INTO pokemons (id, name, height, weight, sprites, moves) VALUES
(1, 'bulbasaur', 7, 69, '{"front_default":"https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/1.png"}'::jsonb, '[{"move":{"name":"razor-wind","url":"https://pokeapi.co/api/v2/move/13/"}},{"move":{"name":"swords-dance","url":"https://pokeapi.co/api/v2/move/14/"}},{"move":{"name":"cut","url":"https://pokeapi.co/api/v2/move/15/"}},{"move":{"name":"bind","url":"https://pokeapi.co/api/v2/move/20/"}},{"move":{"name":"vine-whip","url":"https://pokeapi.co/api/v2/move/22/"}}]'::jsonb),
(2, 'ivysaur', 10, 130, '{"front_default":"https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/2.png"}'::jsonb, '[{"move":{"name":"swords-dance","url":"https://pokeapi.co/api/v2/move/14/"}},{"move":{"name":"cut","url":"https://pokeapi.co/api/v2/move/15/"}},{"move":{"name":"bind","url":"https://pokeapi.co/api/v2/move/20/"}},{"move":{"name":"vine-whip","url":"https://pokeapi.co/api/v2/move/22/"}},{"move":{"name":"headbutt","url":"https://pokeapi.co/api/v2/move/29/"}}]'::jsonb),
(3, 'venusaur', 20, 1000, '{"front_default":"https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/3.png"}'::jsonb, '[{"move":{"name":"swords-dance","url":"https://pokeapi.co/api/v2/move/14/"}},{"move":{"name":"cut","url":"https://pokeapi.co/api/v2/move/15/"}},{"move":{"name":"bind","url":"https://pokeapi.co/api/v2/move/20/"}},{"move":{"name":"vine-whip","url":"https://pokeapi.co/api/v2/move/22/"}},{"move":{"name":"headbutt","url":"https://pokeapi.co/api/v2/move/29/"}}]'::jsonb),
(4, 'charmander', 6, 85, '{"front_default":"https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/4.png"}'::jsonb, '[{"move":{"name":"mega-punch","url":"https://pokeapi.co/api/v2/move/5/"}},{"move":{"name":"fire-punch","url":"https://pokeapi.co/api/v2/move/7/"}},{"move":{"name":"thunder-punch","url":"https://pokeapi.co/api/v2/move/9/"}},{"move":{"name":"scratch","url":"https://pokeapi.co/api/v2/move/10/"}},{"move":{"name":"swords-dance","url":"https://pokeapi.co/api/v2/move/14/"}}]'::jsonb),
(5, 'charmeleon', 11, 190, '{"front_default":"https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/5.png"}'::jsonb, '[{"move":{"name":"mega-punch","url":"https://pokeapi.co/api/v2/move/5/"}},{"move":{"name":"fire-punch","url":"https://pokeapi.co/api/v2/move/7/"}},{"move":{"name":"thunder-punch","url":"https://pokeapi.co/api/v2/move/9/"}},{"move":{"name":"scratch","url":"https://pokeapi.co/api/v2/move/10/"}},{"move":{"name":"swords-dance","url":"https://pokeapi.co/api/v2/move/14/"}}]'::jsonb),
(6, 'charizard', 17, 905, '{"front_default":"https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/6.png"}'::jsonb, '[{"move":{"name":"mega-punch","url":"https://pokeapi.co/api/v2/move/5/"}},{"move":{"name":"fire-punch","url":"https://pokeapi.co/api/v2/move/7/"}},{"move":{"name":"thunder-punch","url":"https://pokeapi.co/api/v2/move/9/"}},{"move":{"name":"scratch","url":"https://pokeapi.co/api/v2/move/10/"}},{"move":{"name":"swords-dance","url":"https://pokeapi.co/api/v2/move/14/"}}]'::jsonb),
(7, 'squirtle', 5, 90, '{"front_default":"https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/7.png"}'::jsonb, '[{"move":{"name":"mega-punch","url":"https://pokeapi.co/api/v2/move/5/"}},{"move":{"name":"ice-punch","url":"https://pokeapi.co/api/v2/move/8/"}},{"move":{"name":"mega-kick","url":"https://pokeapi.co/api/v2/move/25/"}},{"move":{"name":"headbutt","url":"https://pokeapi.co/api/v2/move/29/"}},{"move":{"name":"tackle","url":"https://pokeapi.co/api/v2/move/33/"}}]'::jsonb),
(8, 'wartortle', 10, 225, '{"front_default":"https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/8.png"}'::jsonb, '[{"move":{"name":"mega-punch","url":"https://pokeapi.co/api/v2/move/5/"}},{"move":{"name":"ice-punch","url":"https://pokeapi.co/api/v2/move/8/"}},{"move":{"name":"mega-kick","url":"https://pokeapi.co/api/v2/move/25/"}},{"move":{"name":"headbutt","url":"https://pokeapi.co/api/v2/move/29/"}},{"move":{"name":"tackle","url":"https://pokeapi.co/api/v2/move/33/"}}]'::jsonb),
(9, 'blastoise', 16, 855, '{"front_default":"https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/9.png"}'::jsonb, '[{"move":{"name":"mega-punch","url":"https://pokeapi.co/api/v2/move/5/"}},{"move":{"name":"ice-punch","url":"https://pokeapi.co/api/v2/move/8/"}},{"move":{"name":"mega-kick","url":"https://pokeapi.co/api/v2/move/25/"}},{"move":{"name":"headbutt","url":"https://pokeapi.co/api/v2/move/29/"}},{"move":{"name":"tackle","url":"https://pokeapi.co/api/v2/move/33/"}}]'::jsonb),
(10, 'caterpie', 3, 29, '{"front_default":"https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/10.png"}'::jsonb, '[{"move":{"name":"tackle","url":"https://pokeapi.co/api/v2/move/33/"}},{"move":{"name":"string-shot","url":"https://pokeapi.co/api/v2/move/81/"}},{"move":{"name":"snore","url":"https://pokeapi.co/api/v2/move/173/"}},{"move":{"name":"bug-bite","url":"https://pokeapi.co/api/v2/move/450/"}},{"move":{"name":"electroweb","url":"https://pokeapi.co/api/v2/move/527/"}}]'::jsonb)
ON CONFLICT (id) DO NOTHING;

-- 3. VERIFICAR LOS 10 REGISTROS
SELECT id, name, height, weight FROM pokemons ORDER BY id ASC;
